name: 'DBT_SNOWFLAKE'
version: '1.0.0'


profile: 'DBT_SNOWFLAKE'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"



models:
  DBT_SNOWFLAKE:
  
    bronze:
      +materialized: table  
      +schema: bronze
    silver:
      +materialized: table  
      +schema: silver
    gold:
      +materialized: view  
      +schema: gold