DBT_SNOWFLAKE:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 16
      account: BAEGDNB-UOB31263
      user: MOSAB
      database: DATAWAREHOUS
      warehouse: COMPUTE_WH
      schema: dbt_schema
      password: 0113575575@MAx
      role: ACCOUNTADMIN

    prod:
      type: snowflake
      threads: 16
      account: BAEGDNB-UOB31263
      user: MOSAB
      database: ANALYTICS
      warehouse: COMPUTE_WH
      schema: ANALYTICS_PROD
      password: 0113575575@MAx
      role: ACCOUNTADMIN  
