
SELECT 
    DATE_TRUNC('YEAR', ORDER_DATE) AS ORDER_YEAR,
    SUM(SALES_AMOUNT) AS TOTAL_SALES,
    COUNT(DISTINCT CUSTOMER_KEY) AS TOTAL_CUSTOMERS,
    SUM(QUANTITY) AS TOTAL_QUANTITY
FROM {{ ref('fact_sales') }}
WHERE ORDER_DATE IS NOT NULL
GROUP BY ORDER_YEAR
ORDER BY ORDER_YEAR