WITH CATEGORY_SALES AS (
SELECT 
CATEGORY,
SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM {{ ref('fact_sales') }} s
LEFT JOIN {{ ref('dim_products') }} p
ON s.PROUDACT_KEY = p.PROUDACT_KEY
GROUP BY 1
)

SELECT
CATEGORY,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER () AS OVERALL_SALES,
CONCAT(ROUND((TOTAL_SALES / SUM(TOTAL_SALES) OVER ()) * 100 ,2), '%' )AS PERCENTAGE_OF_TOTAL
FROM CATEGORY_SALES
ORDER BY TOTAL_SALES DESC