/* ANALYSIS THE YEARLY SALES PERFORMANCE OF PRODUCTS BY
 COMPARING THEIR SALES TO BOTH THE AVERAGE SALES PERFORMANCE OF PRODUCTS AND THE PREVIOUS YEAR'S SALES */

WITH yearly_product_sales AS (
SELECT 
   YEAR(s.ORDER_DATE) AS ORDER_YEAR,
   p.PROUDACT_NAME,
   SUM(s.SALES_AMOUNT) AS CURRENT_SALES
FROM {{ ref('fact_sales') }} s
LEFT JOIN {{ ref('dim_products') }} p
ON s.PROUDACT_KEY = p.PROUDACT_KEY
WHERE s.ORDER_DATE IS NOT NULL
GROUP BY 1,2
) 

SELECT 
   ORDER_YEAR,
   PROUDACT_NAME,
   CURRENT_SALES,
   AVG(CURRENT_SALES) OVER (PARTITION BY PROUDACT_NAME) AS AVG_SALES,
   CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PROUDACT_NAME) AS DIFFERENCE_AVG,
   CASE 
       WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PROUDACT_NAME) > 0 THEN 'ABOVE AVERAGE'
       WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PROUDACT_NAME) < 0 THEN 'BELOW AVERAGE'
       ELSE 'AVERAGE' 
   END AS AVG_CHANGE,
   --YEAR OVER YEAR ANALYSIS
   LAG(CURRENT_SALES) OVER (PARTITION BY PROUDACT_NAME ORDER BY ORDER_YEAR) AS PREVIOUS_YEAR_SALES,
   CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PROUDACT_NAME ORDER BY ORDER_YEAR) AS DIFFERENCE_PREVIOUS_YEAR,
   CASE 
         WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PROUDACT_NAME ORDER BY ORDER_YEAR) > 0 THEN 'INCREASE'
         WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PROUDACT_NAME ORDER BY ORDER_YEAR) < 0 THEN 'DECREASE'
         ELSE 'NO CHANGE' 
      END AS PREVIOUS_YEAR_CHANGE
FROM yearly_product_sales
ORDER BY PROUDACT_NAME, ORDER_YEAR