
SELECT 
ROW_NUMBER () OVER (ORDER BY pn.PRD_START_DT,pn.PRD_KEY) AS PROUDACT_KEY,
pn.PRD_ID AS PROUDACT_ID, 
pn.PRD_KEY AS PROUDACT_NUMBER,
pn.PRD_NM AS PROUDACT_NAME,
pn.CAT_ID AS CATEGORY_ID,
pc.CAT  AS CATEGORY,
pc.SUBCAT AS SUBCATEGORY,
pc.MAINTENANCE,
pn.PRD_COST AS COST,
pn.PRD_LINE AS PRODUCT_LINE,
pn.PRD_START_DT AS START_DATE 
FROM {{ ref('silver_crm_prd_info') }} pn 
LEFT JOIN {{ ref('silver_erp_px_cat_g1v2') }} pc 
ON pn.CAT_ID = pc.ID
WHERE PRD_END_DT IS NULL    --FILTERING OUT ALL HISTORICAL DATA 

