SELECT 
    SLS_ORD_NUM,
    SLS_PRD_KEY,
    SLS_CUST_ID,
    CASE 
        WHEN SLS_ORDER_DT = 0 OR LEN(SLS_ORDER_DT) != 8 THEN NULL
        ELSE TO_DATE(TO_VARCHAR(SLS_ORDER_DT), 'YYYYMMDD')
    END AS SLS_ORDER_DT,
     CASE 
        WHEN SLS_SHIP_DT = 0 OR LEN(SLS_SHIP_DT) != 8 THEN NULL
        ELSE TO_DATE(TO_VARCHAR(SLS_SHIP_DT), 'YYYYMMDD')
    END AS SLS_SHIP_DT,
        CASE 
            WHEN SLS_DUE_DT = 0 OR LEN(SLS_DUE_DT) != 8 THEN NULL
            ELSE TO_DATE(TO_VARCHAR(SLS_DUE_DT), 'YYYYMMDD')
        END AS SLS_DUE_DT,
    CASE 
        WHEN SLS_SALES IS NULL OR SLS_SALES <= 0 OR SLS_SALES != SLS_QUANTITY * ABS(SLS_PRICE)
        THEN SLS_QUANTITY * ABS(SLS_PRICE)
        ELSE SLS_SALES
        END AS SLS_SALES,
    SLS_QUANTITY,
     CASE 
        WHEN SLS_PRICE IS NULL OR SLS_PRICE <= 0 
        THEN SLS_SALES / NULLIF(SLS_QUANTITY,0)
        ELSE SLS_PRICE
        END AS SLS_PRICE ,  
    CURRENT_TIMESTAMP() AS dwh_create_date
FROM {{ ref('bronze_crm_sales_details') }}
